// Carga de productos en el ABM
export const START_DESCARGA_PRODUCTOS = 'START_DESCARGA_PRODUCTOS';
export const DESCARGAR_PRODUCTO_EXITO = 'DESCARGAR_PRODUCTO_EXITO';
export const DESCARGAR_PRODUCTO_ERROR = 'DESCARGAR_PRODUCTO_ERROR';

// Alta de productos
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

// Edicion de productos
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const EDITA_PRODUCTO_EXITO = 'EDITA_PRODUCTO_EXITO';
export const EDITA_PRODUCTO_ERROR = 'EDITA_PRODUCTO_ERROR';

// Delete de productos
export const ELIMINA_PRODUCTO_ID = 'ELIMINA_PRODUCTO_ID';
export const ELIMINA_PRODUCTO_EXITO = 'ELIMINA_PRODUCTO_EXITO';
export const ELIMINA_PRODUCTO_ERROR = 'ELIMINA_PRODUCTO_ERROR';

// Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

