// Alta de productos
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

// Carga de productos en el ABM
export const START_DESCARGA_PRODUCTOS = 'START_DESCARGA_PRODUCTOS';
export const DESCARGAR_PRODUCTO_EXITO = 'DESCARGAR_PRODUCTO_EXITO';
export const DESCARGAR_PRODUCTO_ERROR = 'DESCARGAR_PRODUCTO_ERROR';
